### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by SandraKla** [SandraKla/ShinySurfer#1]
https://github.com/SandraKla/ShinySurfer_original/issues

**Comment by PrinceSajjadHussain** [comment]
commit it i send a file to your gmail for your problem

**Comment by SandraKla** [comment]
What problem do you mean more precisely? There are five problems listed under the link ;) 
Have you tried the ShinyApp @PrinceSajjadHussain? I would be glad about feedback. Kind regards, Sandra
